### ISSUE TITLE
Integrate the full KnownVariant DTO in the existing service

### ISSUE THREAD

**Issue by priesgo** [genomicsengland/clinical_variant_ark#13]

**Comment by cboustred** [comment]
DTO?

There is a list of "interesting_variants" being stored here: http://10.0.32.112/labkey/project/VariantDatabase/begin.view?pageId=interesting_variants 

Those that have have been flagged in the category "tiering_whitelist" might be suitable for the Ark

**Comment by priesgo** [comment]
Data Transfer Object (https://en.wikipedia.org/wiki/Data_transfer_object)
These are the Java objects where we are loading the information read or written into from mongoDB.

**Comment by priesgo** [comment]
DTOs were finally replaced by wrappers. But this are fully integrated in the existing service
